#!/bin/bash
echo Enter your username
read username
#curl https://raw.githubusercontent.com/MrFlacko/Scripts/master/mirrorsaustralia > /etc/pacman.d/mirrorlist
pacman -Syyu --noconfirm
pacman -S wget git unzip curl nano --noconfirm
mkdir /home/$username/Videos
mkdir /home/$username/Documents
mkdir /home/$username/Music
mkdir /home/$username/Pictures
mkdir /home/$username/Downloads
cd /home/$username/Downloads
git clone https://aur.archlinux.org/yay.git
cd /home/$username/.vpn
cd /home/$username/Downloads/yay
chown -R $username /home/$username/
sudo -u $username makepkg -si --noconfirm
rm -rv ../yay
cd /home/$username/Downloads
sudo -u $username yay -S teamviewer ocenaudio flameshot qbittorrent-dark-git minecraft-launcher --noconfirm
systemctl enable teamviewerd 
systemctl enable ufw
ufw enable
pacman -S ntfs-3g gvfs-afc gvfs-goa gvfs-google htop gvfs-gphoto2 gvfs-mtp gvfs-mtp gvfs-nfs gvfs-smb nautilus p7zip unzip zip unrar ark thunderbird sl code nomacs deepin-movie net-tools traceroute nmap evince gnome-disk-utility ksysguard obs-studio baobab mousepad spectacle libreoffice-still dia firefox gimp htop peek adobe-source-sans-pro-fonts aspell-en enchant gst-libav gst-plugins-good icedtea-web jre8-openjdk languagetool libmythes mythes-en pkgstats ttf-anonymous-pro ttf-bitstream-vera ttf-dejavu ttf-droid ttf-liberation ttf-ubuntu-font-family intel-ucode ufw w3m nano curl filezilla gimp discord  --noconfirm
systemctl enable libvirtd
