#!/bin/bash
#Can be grabbed from
#wget https://bit.ly/2X6sZVU && bash 2X6sZVU
echo 'Enter your FQDN panel.example.com'
read fqdn
apt install curl vim -y
#curl https://raw.githubusercontent.com/MrFlacko/Scripts/master/UbuntuMirrors18.04 > /etc/apt/sources.list
apt update
apt upgrade -y
bash <(curl -s https://raw.githubusercontent.com/VilhelmPrytz/pterodactyl-installer/master/install-panel.sh)
bash <(curl -s https://raw.githubusercontent.com/VilhelmPrytz/pterodactyl-installer/master/install-daemon.sh)
apt update
apt upgrade -y
apt install certbot
echo 'Certbot running'
echo 'Select create temporary website to configure'
ufw allow 443
ufw allow 80
ufw allow 22
ufw allow 2022
ufw allow 8080
ufw allow 25565
echo y | ufw delete 7
echo y | ufw delete 7
echo y | ufw delete 7
echo y | ufw delete 7
echo y | ufw delete 7
echo y | ufw delete 7
ufw enable
certbot certonly -d $fqdn
systemctl restart nginx
echo done
echo cd /srv/daemon, copy core.json from the website to the config folder when creating the node
echo then do npm start
