#!/bin/bash
#Can be grabbed from
#wget https://bit.ly/2X6sZVU && bash 2X6sZVU
echo 'Enter your FQDN panel.example.com'
read fqdn
curl https://raw.githubusercontent.com/MrFlacko/Scripts/master/UbuntuMirrors18.04 > /etc/apt/sources.list
apt update
apt upgrade -y
bash <(curl -s https://raw.githubusercontent.com/VilhelmPrytz/pterodactyl-installer/master/install-panel.sh)
bash <(curl -s https://raw.githubusercontent.com/VilhelmPrytz/pterodactyl-installer/master/install-daemon.sh)
apt update
apt upgrade -y
apt install certbot
echo 'Certbot running'
echo 'Select create temporary website to configure'
certbot certonly -d $fqdn
echo remember to place your core.json from your web panel in /srv/daemon/core.json and replace the http://index.html to https://$fqdn" 
echo once done, run npm start in the /srv/daemon directory
echo done
