#!/bin/bash
#Can be grabbed from
#wget https://bit.ly/2X6sZVU && bash 2X6sZVU
echo 'Enter your FQDN panel.example.com'
read fqdn
curl https://raw.githubusercontent.com/MrFlacko/Scripts/master/UbuntuMirrors18.04 > /etc/apt/sources.list
apt update
apt upgrade -y
bash <(curl -s https://raw.githubusercontent.com/VilhelmPrytz/pterodactyl-installer/master/install-panel.sh)
bash <(curl -s https://raw.githubusercontent.com/VilhelmPrytz/pterodactyl-installer/master/install-daemon.sh)
apt update
apt upgrade -y
apt install certbot
echo 'Certbot running'
echo 'Select create temporary website to configure'
ufw allow 443
ufw allow 80
ufw allow 22
ufw allow 25565
echo y | ufw delete 5
echo y | ufw delete 5
echo y | ufw delete 5
echo y | ufw delete 5
ufw enable
certbot certonly -d $fqdn
echo done
